### ISSUE TITLE
Sub-filter production should use the full velocity gradient tensor

### ISSUE THREAD

**Issue by clarkpede** [pecos-hybrid/SU2#35]
This was discussed via email, but I'm putting it here so we can track the issue better.

In the incompressible limit, P_{ij} = 1/2 (tau_{ik} \partial u_k \partial x_j + tau_{jk} \partial u_k \partial x_i).  "tau" is the combination of SGS and SGET terms. When compressiblity is factored in, it seems like we should still be using the velocity gradient tensor (and not the deviatoric velocity gradient tensor).  The definition of tau should shift to use a deviatoric rate-of-strain, but the velocity gradient tensor shouldn't if we're trying to be consistent with the typical definition of production.  In SU2, the SGS contibution to the production tensor is effectively tau^{SGS} times the resolved deviatoric velocity gradient tensor.  You can see this yourself by noticing that there are terms with "eddy_viscosity" and "Sd" (where "Sd" is the resolved deviatoric rate-of-strain tensor). That stands in contrast to the tau^{SGET} terms, which use "Gt", the full velocity gradient tensor.  I believe the tau^{SGS} terms are wrong, and should be corrected to use the full (not deviatoric) strain and velocity gradients.

**Comment by trevilo** [comment]
Just to add a bit of context, I agree that P_{ij} as implemented is incomplete.  None of the terms there are wrong, but a term is missing, specifically div(u)*tauSGS_{ij}/3 I think.  As noted, this is exactly zero for incompressible.  The reason it was left out of the initial implementation is that it can produce or destroy turbulence.  I suppose that is fine, but we need to think about what it means if we get a negative eigenvalue out of this procedure.

**Comment by clarkpede** [comment]
Resolved by 156446fc79c5c450e6e3cfcf9c1ad24a069f430f
